### ISSUE TITLE
Callback for 'register' action never called in Android plugin 

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#1]
Js callback is never triggered when register new user.
There is a message in logcat: "Got an activity result, but no plugin was registered to receive it"

To fix it need to add 
cordova.setActivityResultCallback(this);
before calling 
activity.startActivityForResult(intent, requestCode);

**Comment by jakubdolejs** [comment]
Fixed
