### ISSUE TITLE
Ver-ID is not loading

### ISSUE THREAD

**Issue by bmonson** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#10]
Ver-ID load is failing when the code below runs in my app, and the error returned is null. The code below generates an alert that says "failed: null". Without a good error message I'm not sure what could be causing the problem.

```
verid.load("my_api_secret").then(function () {
	// Ver-ID loaded successfully
	// You can now run registration, authentication or liveness detection
	navigator.notification.alert("loaded");
}).catch(function (error) {
	// Ver-ID failed to load
	navigator.notification.alert("failed: "+JSON.stringify(error));
});
```

**Comment by jakubdolejs** [comment]
Hi @bmonson,

Error messages have been added in 983ed43fe14e87637b5be4512a8dc82b25327aa4.

1. Check that you are using a valid API secret for your bundle id/package name. I'm assuming that you entered "my_api_secret" just as a placeholder.
2. Bear in mind that any errors thrown within the `then` block will be caught in the `catch` block. For example when I tested it with the above code I didn't have the `notification` object. As a result the load operation succeeded but JavaScript threw an error that propagated into the catch block.

    In the following example the console will output both "Ver-ID loaded" and "Received an error null".
    
    ```javascript
    verid.load("my_api_secret").then(function () {
        console.log("Ver-ID loaded");
        // The following will invoke the catch block below
        throw null;
    }).catch(function (error) {
        // error will be null
        console.log("Received an error", error);
    });
    ```

**Comment by bmonson** [comment]
I am using the API secret that I was provided, and I am not including any commands in the `then` callback that would throw an error. Now that you've added error messages, I am getting this error:

`The operation couldn't be completed. (VerID.ResourceLoader.ResourceLoaderError error 5.)`

**Comment by jakubdolejs** [comment]
Hi @bmonson,
This error points to a problem with the VerIDModels folder. Can you check that the folder is present in the project and that it's not empty? When you clone the plugin from Git you have to make sure you use the `--recurse-submodules` flag to clone the contents of the folder.
Jakub

**Comment by bmonson** [comment]
I used the `--recurse-submodules` flag, and the repository cloned to a local directory with the VerIDModels folder. That folder is also in my app/plugins/com-appliedrec-plugins-verid folder, but not in app/platforms/ios/www/plugins/com-appliedrec-plugins-verid folder. The only thing in my platform plugin folder is www/Ver-ID.js. Do I need a `before_build` hook to move these to my plugins folder?

**Comment by jakubdolejs** [comment]
The plugin should automatically copy the VerIDModels directory into these locations:
- **iOS:** [project root]/platforms/ios/[project name]/Resources
- **Android:** [project root]/platforms/android/app/src/main/assets
Can you check these folders please? Let me know how it goes.

**Comment by bmonson** [comment]
I'm not building for android at the moment. The Resources folder under the iOS platform does not have the VerIDModels files.

**Comment by jakubdolejs** [comment]
Can you confirm that the folder appears in the Resources group of your Xcode project:
![image](https://user-images.githubusercontent.com/849856/52006813-f559be00-24c4-11e9-9123-d586dece23de.png)
And that it's a member of your app's target:
![image](https://user-images.githubusercontent.com/849856/52006929-38b42c80-24c5-11e9-9d69-4d0101a486b0.png)

If the above is ok. Can you please save this into a file (e.g. file_hash.py):
```python
import os
import hashlib
import sys

if len(sys.argv) < 2:
    print 'Missing arguments. Correct syntax: ' + sys.argv[0] + ' file'
    sys.exit(1)
FILE_PATH = sys.argv[1]

def hashfile(afile, hasher, blocksize=65536):
    buf = afile.read(blocksize)
    while len(buf) > 0:
        hasher.update(buf)
        buf = afile.read(blocksize)
    return hasher.hexdigest()

with file(FILE_PATH, "rb") as f:
        hash = hashfile(f, hashlib.sha256())
        print hash
```
and run it with Python 2.7 for each file (except the .git* files) in the VerIDModels folder? The syntax is `python file_hash.py <file_name>`. The script will output a hash of the file. The hashes of the files should correspond to this:
```
haarcascade_mcs_righteye.xml:
4039e639a4efd0862a25b45ffe0cede3e21ab4eded8b3f815ce352bf475b2ca7

fhogcascade_face_frontal.dat:
f3f7aa833fb4a14a46fc48689f45b98d85ef72d6dfaf8bdc012b7d3c522a5426

shape_predictor_68_face_landmarks.dat:
0a9bc8ed80a40a5c06b456c2d9e1244402d8d940b23566cfaf1a685781ff63d3

mmod_human_face_detector.dat:
be467b1a76f482693de3b0f6a1ff91d092319be71523d4d4b0628f6a53fcb87a

haarcascade_smile.xml:
e371408193757aa85c13d365fff83b9b1c14f4427f1562cc72b4f3613bed63bd

dlib_face_recognition_resnet_model_v1.dat:
51f33b6975c5752542cf04f4fe211ddea3a3abca438847ab16d859b79fbbe927

haarcascade_mcs_lefteye.xml:
b80b5e7d819fa23bb1a0ea7eeae54e7362c2bf8befa33c2c5fcec89e84ecf4ba
```
If they don't then the files may be corrupted. It happened to some users that Git overwrote the line feed characters `\n` with Windows version `\r\n`. The resulting hash of the file was different.

If the hashes the script generates are different from the ones above, can you please download [the source](https://github.com/AppliedRecognition/Ver-ID-Models) as a zip archive, unzip it in the Resources folder and try the script again?

**Comment by bmonson** [comment]
All of the hashes were incorrect; however, after downloading the source models as a zip archive and running your python script again I still get the incorrect hashes:

```
haarcascade_mcs_righteye.xml
b6e175eca440aa41219050397e859491ddd074089d8b2da4b37c7f37d2eaf977

fhogcascade_face_frontal.dat
8165c8f3af7e7dd99bbec40598f33a5e02b24aafa7fe39e9c6d52d40a28f6bb0

shape_predictor_68_face_landmarks.dat
a41d3ce1a03f8f9d70441628d10f6c8f6c075e6698f8341edc3cebc856d85688

mmod_human_face_detector.dat
f6aef8952f91afcc0bdf68a4d041998c768a38a33ca972f513da7932334ae0b8

haarcascade_smile.xml
0cdf4fcc266e01fa4baea35393083dc7d07172f151aff97c831c42b8ae5d54c1

dlib_face_recognition_resnet_model_v1.dat
3051f23651f1a134a83d4a95dfd15c07596d5e42745487478d7a2135de40db6b

haarcascade_mcs_lefteye.xml
c753f225762ed3d665d29e7dae0de73e32f48675762db4f0a2af3306cd92c178
```

**Comment by jakubdolejs** [comment]
@bmonson, do you mind attaching one of the XML files here? Doesn't matter which one. I just cloned the plugin and added it to a new project and the hashes checked out. I'm curious to see what's different. Thanks.

**Comment by bmonson** [comment]
I had to zip the file because .xml is not a file type I can upload, apparently...

[haarcascade_mcs_lefteye.xml.zip](https://github.com/AppliedRecognition/Ver-ID-Person-Cordova-Plugin/files/2822515/haarcascade_mcs_lefteye.xml.zip)

**Comment by jakubdolejs** [comment]
Thanks @bmonson, Makes sense now. You have to install and enable [Git LFS](https://git-lfs.github.com). The content of your XML is simply a reference to the object in LFS:
```
version https://git-lfs.github.com/spec/v1
oid sha256:b80b5e7d819fa23bb1a0ea7eeae54e7362c2bf8befa33c2c5fcec89e84ecf4ba
size 777721
```

**Comment by bmonson** [comment]
Thank you, that did the trick.
