### ISSUE TITLE
Can not reach the library comes from pod

### ISSUE THREAD

**Issue by gurhangure** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#15]
Hello, first of all when I "pod install" I get this warning (which cause to my main problem I guess) on the macos terminal "The `Biometric Control [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Biometric Control/Pods-Biometric Control.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target."

Then, when I launch my app (Biometric Control), I get instant crush with this error on xcode terminal  "dyld: Library not loaded: @rpath/VerIDSDKIdentity.framework/VerIDSDKIdentity
  Referenced from: /Users/utis/Library/Developer/CoreSimulator/Devices/24574472-A47C-4DB5-9B35-64AD86828250/data/Containers/Bundle/Application/A28B61EF-A1FD-437D-805A-8E440D5431D9/Biometric Control.app/Frameworks/VerIDCore.framework/VerIDCore
  Reason: image not found
(lldb) "

I tried many suggested solutions online but having this problem for 1 week, maybe you have a solution I hope thanks.

**Comment by jakubdolejs** [comment]
Hello @gurhangure, 
Thank you for reporting this and for trying out the Cordova plugin. 
We're in the process of updating the plugin and there will be a new release coming up in the next few weeks.
In the meantime, can you please try adding the following CocoaPod dependency in the project's Podfile?

```
pod 'Ver-ID-SDK-Identity', '~> 3.0'
```
Thank you,
Jakub

**Comment by gurhangure** [comment]
That made my pod to add the library "Ver-ID-SDK-Identity" but problem continues

**Comment by jakubdolejs** [comment]
Hi @gurhangure, 
We're aiming for a new release at the beginning of June. It will come with a sample app.
Cheers,
Jakub

**Comment by gurhangure** [comment]
Nice I will try it, closing the issue now ty for help.
