### ISSUE TITLE
VerIDPlugin.java won't compile

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#2]
Android plugin won't compile

**Comment by jakubdolejs** [comment]
b8c8d9dc8e5b42127eed1470129a065bf52e34c3 compiles after adjusting some properties in the gradle build files. Please see [documentation](https://appliedrecognition.github.io/Ver-ID-Person-Cordova-Plugin/index.html) on how to set up Android projects.

You will need to add parameters to the `android/defaultConfig` section in the app module's **gradle.build** file:
~~~groovy
multiDexEnabled true
renderscriptTargetApi 14
renderscriptSupportModeEnabled true
~~~
