### ISSUE TITLE
Invalid values if Bearings and LivenessDetection enums

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#3]
Could not use values of veridPlugin.Bearings/veridPlugin.LivenessDetection enum due to exception "No enum constant com.appliedrec.ver_id.VerID.Bearing."
Solution: edit enum values - replace int values with string values

**Comment by jakubdolejs** [comment]
Serialisation of the `Bearing` and `LivenessDetection` enums has been redone in 3.0.0 b8c8d9dc8e5b42127eed1470129a065bf52e34c3. See [documentation](https://appliedrecognition.github.io/Ver-ID-Person-Cordova-Plugin/module-verid.html) for details.
