### ISSUE TITLE
Inherited fields of setting objects are lost while providing to native layer

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#4]
JSON.stringify returns only values of current object but not his prototype.
So if LivenessDetectionSessionSettings extends SessionSettings then native layer will receive only keys defined in LivenessDetectionSessionSettings.
Only flat object allowed to be used as arguments of exec function.
Solution: flatten a setting object before calling exec function

**Comment by jakubdolejs** [comment]
JSON serialisation has been refactored in b8c8d9dc8e5b42127eed1470129a065bf52e34c3
