### ISSUE TITLE
Do not copy VerIDModels.zip manually

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#5]
Cordova plugin engine provides tools to copy static assets using plugin.xml declaration

**Comment by jakubdolejs** [comment]
As of version 3.0.0 b8c8d9dc8e5b42127eed1470129a065bf52e34c3 [VerIDModels](https://github.com/AppliedRecognition/Ver-ID-Models/tree/dbe70619bbd69b9dc108dfd711ee9f9136d58184) is included in the plugin as a submodule.
