### ISSUE TITLE
Handling Cancel callback

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Person-Cordova-Plugin#6]
User can press back button (Android) or Cancel button (iOS) to cancel face capturing 
By this action Android plugin calls error callback instead of success callback with Cancel status as it works on iOS
iOS plugin call success callback but provide int value instead of string value: {outcome: 3}
Expected behaviour: cancel action trigger success callback with {outcome:"CANCEL"} option

**Comment by jakubdolejs** [comment]
Fixed in b8c8d9dc8e5b42127eed1470129a065bf52e34c3
